### ISSUE TITLE
Use result in size property

### ISSUE THREAD

**Issue by simonschllng** [jfjlaros/bin-parser#3]
block_name_length returns 7. Using it in size below throws an error. How can this be achieved correctly?

````
- name: CEmbOne
  structure:
  - name: block_name_length
    type: int
    size: 2
  - name: block_name
    type: text
    size: 7 #block_name_length
````
